<a href="https://colab.research.google.com/github/moinul7002/TensorFlow-Basics/blob/main/TF_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
hello = tf.constant('Hello, TensorFlow World!')

In [ ]:
tf.print(hello)

Hello, TensorFlow World!


In [ ]:
a = tf.constant(6, name='constant_a')
b = tf.constant(3, name='constant_b')
c = tf.constant(10, name='constant_c')
d = tf.constant(5, name='constant_d')

In [ ]:
mul = tf.multiply(a,b, name='mul')
div = tf.divide(c,d, name='div')


In [ ]:
print(div)

tf.Tensor(2.0, shape=(), dtype=float64)


In [ ]:
print(mul)

tf.Tensor(18, shape=(), dtype=int32)


In [ ]:
addn = tf.add(mul, tf.cast(div, tf.int32), name='addn')

In [ ]:
print(addn)

tf.Tensor(20, shape=(), dtype=int32)


In [ ]:
sess = tf.compat.v1.Session()


In [ ]:
print(tf.__version__)

2.2.0


In [ ]:
tf.print(addn)

20


In [ ]:
tf.print(mul)
tf.print(div)

18
2


In [ ]:
a = tf.constant(6.5, name='constant_a')
b = tf.constant(3.4, name='constant_b')
c = tf.constant(3.0, name='constant_c')
d = tf.constant(100.2, name='constant_d')

In [ ]:
square = tf.square(a, name ='square_a')

In [ ]:
power = tf.pow(b,c, name ='power_b_c')

In [ ]:
sqrt = tf.sqrt(d, name ='sqrt_a')

In [ ]:
final_sum = tf.add_n([square, power, sqrt], name = 'final_sum')

In [ ]:
tf.print('Square of a: ', square)

Square of a:  42.25


In [ ]:
tf.print('Power of b^c: ', power)

Power of b^c:  39.3040047


In [ ]:
tf.print('Square root of d: ', sqrt)

Square root of d:  10.0099945


In [ ]:
tf.print('Final Sum: ', final_sum)

Final Sum:  91.5639954


In [ ]:
sess.close()

In [ ]:
zeroD = tf.constant(5)

In [ ]:
tf.rank(zeroD)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
oneD = tf.constant(['How','are', 'you?'])
tf.rank(oneD)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
twoD = tf.constant([[1.0,2.3],[1.5,2.9]])
tf.rank(twoD)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
threeD = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]])
tf.rank(threeD)


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.shape(threeD)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>

In [ ]:
tf.compat.v1.disable_eager_execution()

In [ ]:
x = tf.compat.v1.placeholder(tf.int32, shape=[3], name='x')

In [ ]:
y = tf.compat.v1.placeholder(tf.int32, shape=[3], name='y')

In [ ]:
sum_x = tf.reduce_sum(x, name = 'sum_x')

In [ ]:
prod_y= tf.reduce_prod(y, name = 'prod_y')

In [ ]:
final_div = tf.divide(sum_x, prod_y, name = 'final_div')

In [ ]:
final_mean = tf.reduce_mean([sum_x, prod_y], name = 'final_mean')

In [ ]:
sess = tf.compat.v1.Session()

In [ ]:
print('Sum(x): ', sess.run(sum_x, feed_dict = {x: [100, 200, 300]}))

Sum(x):  600


In [ ]:
print('Prod(y): ', sess.run(prod_y, feed_dict = {y: [1,2,3]}))

Prod(y):  6


In [ ]:
print('Sum(x) / Prod(y): ', sess.run(final_div, feed_dict = {x: [10,20,30], y: [1,2,3]}))

 Sum(x) / Prod(y):  10.0


In [ ]:
print('mean(Sum(x) / Prod(y)): ', sess.run(final_mean, feed_dict = {x: [1000,2000,3000], y: [10,20,30]}))

mean(Sum(x) / Prod(y)):  6000


# y = Wx + b
# y_ = x - b

In [ ]:
W = tf.constant([10,100], name = 'const_W')

In [ ]:
x = tf.compat.v1.placeholder(tf.int32, name = 'x')

In [ ]:
b = tf.compat.v1.placeholder(tf.int32, name = 'b')

In [ ]:
Wx = tf.multiply(W,x, name = 'Wx')

In [ ]:
y = tf.add(Wx,b, name = 'y')

In [ ]:
y_ = tf.subtract(x,b, name = 'y_')

In [ ]:
with tf.compat.v1.Session() as sess:
    print('Intermediate Result: Wx = ', sess.run(Wx, feed_dict = {x: [3,33]}))
    print('Intermediate Result: Wx + b = ', sess.run(y, feed_dict = {x: [4,40], b: [7,9]}))
    print('Intermediate Specified: Wx + b = ', sess.run(y, feed_dict = {Wx: [100,1000], b: [7,9]}))
    print('Two Results: [Wx + b, x - b] = ', sess.run(fetches = [y, y_], feed_dict = {x: [4,40], b: [7,9]}))    


Intermediate Result: Wx =  [  30 3300]
Intermediate Result: Wx + b =  [  47 4009]
Intermediate Specified: Wx + b =  [ 107 1009]
Two Results: [Wx + b, x - b] =  [array([  47, 4009], dtype=int32), array([-3, 31], dtype=int32)]


In [ ]:
W = tf.Variable([2.4, 4.0], tf.float32, name = 'var_W')

x = tf.compat.v1.placeholder(tf.float32, name = 'x')
b = tf.Variable([6.0, 10.0], tf.float32, name = 'var_b')

y = W*x + b

In [ ]:
init = tf.compat.v1.global_variables_initializer()

In [ ]:
with tf.compat.v1.Session() as sess:
    sess.run(init)

    print('Final Result: Wx + b = ', sess.run(y, feed_dict = {x: [10, 100]}))

Final Result: Wx + b =  [ 30. 410.]


In [ ]:
s = W*x

init = tf.compat.v1.variables_initializer([W]) 
# initialize only those variables that you might need

In [ ]:
with tf.compat.v1.Session() as sess:
    sess.run(init)

    print('Result: Wx = ', sess.run(s, feed_dict = {x: [10, 100]}))    

Result: Wx =  [ 24. 400.]


In [ ]:
number = tf.Variable(2)
multiplier = tf.Variable(1)

In [ ]:
init = tf.compat.v1.global_variables_initializer()

In [ ]:
result = number.assign(tf.multiply(number, multiplier))

In [ ]:
with tf.compat.v1.Session() as sess:
    sess.run(init)

    for  i in range(10):
        print('Result: ', sess.run(result))
        print('Increment Multiplier: ', sess.run(multiplier.assign_add(1)))

Result:  2
Increment Multiplier:  2
Result:  4
Increment Multiplier:  3
Result:  12
Increment Multiplier:  4
Result:  48
Increment Multiplier:  5
Result:  240
Increment Multiplier:  6
Result:  1440
Increment Multiplier:  7
Result:  10080
Increment Multiplier:  8
Result:  80640
Increment Multiplier:  9
Result:  725760
Increment Multiplier:  10
Result:  7257600
Increment Multiplier:  11


In [ ]:
g = tf.Graph()

In [ ]:
with g.as_default():
    with tf.compat.v1.Session() as sess:
        #y = Ax + b
        A = tf.constant([4,7], tf.int32, name = 'A')

        x = tf.compat.v1.placeholder(tf.int32, name = 'x')

        b = tf.constant([3,4], tf.int32, name = 'b')

        y= A * x + b

        print(sess.run(y, feed_dict = {x: [10,100]}))

        assert y.graph is g

[ 43 704]


In [ ]:
g2 = tf.Graph()

with g2.as_default():
    with tf.compat.v1.Session() as sess:
        A = tf.constant([6,7], tf.int32, name = 'A')

        x = tf.compat.v1.placeholder(tf.int32, name = 'x')

        y = tf.pow(A,x, name = 'y')

        print(sess.run(y, feed_dict = {x: [3,7]}))

        assert y.graph is g2

[   216 823543]


In [ ]:
default_graph = tf.compat.v1.get_default_graph()
with tf.compat.v1.Session() as sess:
    A = tf.constant([6,7], tf.int32, name = 'A')

    x = tf.compat.v1.placeholder(tf.int32, name = 'x')

    y = A + x

    print(sess.run(y, feed_dict = {x: [3,7]}))

    assert y.graph is default_graph

[ 9 14]


In [ ]:
sess = tf.compat.v1.InteractiveSession()

A = tf.constant([4], tf.int32, name = 'A')

x = tf.compat.v1.placeholder(tf.int32, name = 'x')

y = A * x

print(y.eval(feed_dict = {x: [8]}))

sess.close()

[32]


/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
